"""Regenerate the bundled voice on macOS; normal builds use the checked-in asset.

Uses only the installed Samantha voice and Apple's local audio tools. No network.
Each cue is recorded separately so pattern animals can be spoken in any order.
"""
import array
import base64
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import wave

ROOT = Path(__file__).resolve().parent.parent
RATE = 22050
phrases = json.loads((ROOT / "scripts/shape-narration.json").read_text())
clips = []
frames = bytearray()
with tempfile.TemporaryDirectory(prefix="math-garden-voice-") as temp:
    temp = Path(temp)
    for index, phrase in enumerate(phrases):
        clip = temp / "clip.wav"
        subprocess.run([
            "say", "-v", "Samantha", "-r", "155", "-o", str(clip),
            "--file-format=WAVE", f"--data-format=LEI16@{RATE}", phrase,
        ], check=True)
        with wave.open(str(clip)) as wav:
            assert (wav.getnchannels(), wav.getsampwidth(), wav.getframerate()) == (1, 2, RATE)
            pcm = wav.readframes(wav.getnframes())
        samples = array.array("h", pcm)
        if sys.byteorder != "little":
            samples.byteswap()
        assert max(abs(s) for s in samples) > 500, f"Silent recording: {phrase}"
        # Keep a small natural pause, but remove the synthesizer's long trailing silence.
        active = [i for i, sample in enumerate(samples) if abs(sample) > 120]
        first = max(0, active[0] - int(RATE * .04))
        last = min(len(samples), active[-1] + int(RATE * .14))
        pcm = pcm[first * 2:last * 2]
        clips.append([phrase, len(frames) / 2 / RATE, len(pcm) / 2 / RATE])
        frames.extend(pcm)
        if (index + 1) % 10 == 0:
            print(f"Recorded {index + 1}/{len(phrases)} phrases", flush=True)
    wav_path = temp / "narration.wav"
    with wave.open(str(wav_path), "wb") as wav:
        wav.setparams((1, 2, RATE, 0, "NONE", "not compressed"))
        wav.writeframes(frames)
    audio = temp / "narration.m4a"
    subprocess.run(["afconvert", str(wav_path), str(audio), "-f", "m4af", "-d", "aac", "-b", "48000"], check=True)
    # Decode the actual compressed deliverable to catch damaged/empty audio.
    decoded = temp / "decoded.wav"
    subprocess.run(["afconvert", str(audio), str(decoded), "-f", "WAVE", "-d", "LEI16"], check=True)
    with wave.open(str(decoded)) as wav:
        assert wav.getnframes() >= len(frames) // 2
        for phrase, start, duration in clips:
            wav.setpos(round(start * RATE))
            data = array.array("h", wav.readframes(round(duration * RATE)))
            assert max(abs(s) for s in data) > 500, f"Silent encoded cue: {phrase}"
    bundle = {"clips": clips, "audio": base64.b64encode(audio.read_bytes()).decode()}
    output = ROOT / "src/shape-voice-data.js"
    output.write_text('// Generated by scripts/record-shape-narration.py; do not edit audio by hand.\n"use strict";\nconst SHAPE_VOICE_DATA = ' + json.dumps(bundle, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"Saved {len(clips)} verified recordings, {len(frames) / 2 / RATE:.1f} seconds, {output.stat().st_size:,} bytes")
